### ISSUE TITLE
metrics available with this exporter

### ISSUE THREAD

**Issue by sgu-fai** [sapcc/mosquitto-exporter#15]
Hello,

is there a list of metrics available with this exporter ?

Thank you

**Comment by ArtieReus** [comment]
Please have a look here:
https://github.com/sapcc/mosquitto-exporter/blob/master/main.go#L24
Best
A

**Comment by sgu-fai** [comment]
Hello,

your exporter is using client/active or clients/connected ? why not updating it ?
"$SYS/broker/clients/active":   "deprecated in favour of $SYS/broker/clients/connected",
I mean client/connected is collected ?

**Comment by ArtieReus** [comment]
Hi,
the exporter is actually ignoring such metrics. This metrics are grouped here to be ignored:
https://github.com/sapcc/mosquitto-exporter/blob/master/main.go#L24

Connected clients are collected here:
https://github.com/sapcc/mosquitto-exporter/blob/master/main.go#L42
