### ISSUE TITLE
github.com/codegangsta/cli seems to be missing in vendor

### ISSUE THREAD

**Issue by olcai** [sapcc/mosquitto-exporter#3]
Hi and thank you for the exporter!

I'm trying to build it with the Nix package manager, and it seems to me (a Go novice) that the `vendor/` directory is missing something. I get the following while building:

```
go/src/github.com/sapcc/mosquitto-exporter/main.go:12:2: cannot find package "github.com/codegangsta/cli" in any of:
        /tmp/nix-build-mosquitto_exporter-v0.2.0.drv-0/go/src/github.com/sapcc/mosquitto-exporter/vendor/github.com/codegangsta/cli (vendor tree)
```

Is this just me missing something silly, or should the `github.com/codegangsta/cli` be present in `vendor/`?

**Comment by auhlig** [comment]
Better with a20a66e0bcfd40f4b664432ad12eae9ef39e6a2b @olcai?

**Comment by olcai** [comment]
@auhlig: yes, it builds now. Thank you!
