### ISSUE TITLE
Docker error - manifest unknown

### ISSUE THREAD

**Issue by zubairov** [sapcc/mosquitto-exporter#32]
Unfortunately can't download docker image from Dockerhub:

```
~> docker run \
                            -e BROKER_ENDPOINT=tcp://mosquitto:1883 \
                            -p 9234:9234 sapcc/mosquitto-exporter
Unable to find image 'sapcc/mosquitto-exporter:latest' locally
docker: Error response from daemon: manifest for sapcc/mosquitto-exporter:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

**Comment by Legion2** [comment]
On which platform are you running the command (x86, arm7,arm64...)?

**Comment by sxueck** [comment]
use sapcc/mosquitto-exporter:0.6.0
https://hub.docker.com/r/sapcc/mosquitto-exporter/tags?page=1&ordering=last_updated

**Comment by esin** [comment]
Looks like CI didn't tag latest version
@ArtieReus please :) tag sapcc/mosquitto-exporter:latest

**Comment by ArtieReus** [comment]
Fixed!
