### ISSUE TITLE
Makefile utterly broken

### ISSUE THREAD

**Issue by Rudd-O** [sapcc/mosquitto-exporter#4]
Download release.  Unpack.  Make build.

Doesn't work.

**Comment by databus23** [comment]
Rude. Unfriendly. No actionable information.

Really doesn't work.

**Comment by Rudd-O** [comment]
I'll add more information today.  I was very succinct because I was in the middle of a meeting — if that was perceived as rude, I apologize.  We'll work it out for your repo, though my local fork already has been fixed in a way that wouldn't work for your public repo.

On October 3, 2017 10:47:29 PM GMT+02:00, Fabian Ruff <notifications@github.com> wrote:
>Rude. Unfriendly. No actionable information.
>
>Really doesn't work.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sapcc/mosquitto-exporter/issues/4#issuecomment-333973374

--

Rudd-O

http://rudd-o.com/
